#include "gpio.h"

void GPIOA_Init_Direct(void)
{
    *(uint32_t *)(0x40023800UL + 0x30UL) |= (1UL << 0); // GPIOA Clock enable
    *(uint32_t *)(0x40020000UL + 0x00UL) &= ~(0b11UL << 2); // Reset GPIOA MODER1
    *(uint32_t *)(0x40020000UL + 0x00UL) |= (0b01UL << 2);  // Set 01 (output mode)
    *(uint32_t *)(0x40020000UL + 0x04UL) &= ~(1UL << 1);    // Reset Bit1 of GPIOA_OTYPER (push-pull)
    *(uint32_t *)(0x40020000UL + 0x08UL) &= ~(0b11UL << 2); // Reset bits 3 and 2 of GPIOA_OSPEEDR
    *(uint32_t *)(0x40020000UL + 0x08UL) |= (0b01UL << 2);  // Set 01 (Medium speed)
    *(uint32_t *)(0x40020000UL + 0x0CUL) &= ~(0b11UL << 2); // Reset bits 3 and 2 of GPIOA_PUPDR
    *(uint32_t *)(0x40020000UL + 0x18UL) = (1UL << (1 + 16)); // Reset pin via GPIOA_BSRR
}

void GPIOB_Init_Macro(void) {
    MY_PERIPH_RCC_AHB1ENR |= MY_RCC_GPIOB_EN_BIT;
    MY_PERIPH_GPIOB_MODER &= ~MY_PIN1_MODER_CLEAR_MASK;
    MY_PERIPH_GPIOB_MODER |= MY_PIN1_MODER_OUTPUT;
    MY_PERIPH_GPIOB_OTYPER &= ~MY_PIN1_OTYPER_CLEAR_MASK;
    MY_PERIPH_GPIOB_OSPEEDR &= ~MY_PIN1_OSPEEDR_CLEAR_MASK;
    MY_PERIPH_GPIOB_OSPEEDR |= MY_PIN1_OSPEEDR_MEDIUM;
    MY_PERIPH_GPIOB_PUPDR &= ~MY_PIN1_PUPDR_CLEAR_MASK;
}

void GPIOC_Init_CMSIS(void) {
    SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOCEN);
    CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODER0_Msk | GPIO_MODER_MODER1_Msk);
    CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPD0_Msk | GPIO_PUPDR_PUPD1_Msk);
    CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODER2_Msk);
    SET_BIT(GPIOC->MODER, GPIO_MODER_MODER2_0);
    CLEAR_BIT(GPIOC->OTYPER, GPIO_OTYPER_OT2_Msk); 
    CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPD2_Msk);
    CLEAR_BIT(GPIOC->OSPEEDR, GPIO_OSPEEDR_OSPEED2_Msk);
    SET_BIT(GPIOC->OSPEEDR, GPIO_OSPEEDR_OSPEED2_0);
}